---

- name: Basic configuration for ansible_nodes servers
  hosts: ansible_nodes
  gather_facts: false
  connection: local
  tasks:
    - name: ensure .ssh directory exists
      file:
        path: ~/.ssh
        mode: 0700
        state: directory
    - name: ensure known_hosts file exists
      copy:
        content: ""
        dest: ~/.ssh/known_hosts
        mode: 0600
    - name: "check if known_hosts contains server's fingerprint"
      command: ssh-keygen -F {{ inventory_hostname }}
      register: keygen
      failed_when: keygen.stderr != ''
      changed_when: false

    - name: fetch remote ssh key
      command: ssh-keyscan -T5 {{ inventory_hostname }}
      register: keyscan
      failed_when: keyscan.rc != 0 or keyscan.stdout == ''
      changed_when: false
      when: keygen.rc == 1

    - name: add ssh-key to local known_hosts
      lineinfile:
        name: ~/.ssh/known_hosts
        create: true
        line: "{{ item }}"
        mode: '0600'
      when: keygen.rc == 1
      with_items: '{{ keyscan.stdout_lines|default([]) }}'
      no_log: true

- name: Ensure Apache is installed with the correct modules
  hosts: ansible_nodes
  become: true
  tasks:
  - name: yum update
    action: yum name=* state=latest
  - name: Ensure Apache is installed
    yum: name=httpd state=present
    become: true
  - name: yum install epel
    yum: name=epel-release.noarch state=latest
  - name: download remi repo rpm
    get_url: url=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm dest=/root/  
  - name: install remi repo rpm
    yum: name=/root/remi-release-7.rpm state=present
  - name: install php
    yum: enablerepo=remi,remi-php56 name=php-mssql,php-pear,php,php-pdo,php-pecl-redis,php-xml,php-pecl-zip,php-pecl-jsonc,php-pecl-igbinary,httpd,httpd-tools,php-mbstring state=latest
  - name: install rsync
    yum: name=rsync state=latest
  - name: Ensure MySql Module for Apache is installed
    package: name=mysql-community-server state=present
    ignore_errors: true

- name: Deploy the application-package
  hosts: ansible_nodes
  tasks:
  - name: Install PHP File
    copy:
      src: files/index.php
      dest: /var/www/html/index.php
      owner: ansible
      group: ansible
      mode: '0644'
    become: true
  - name: Ensure default HTML file does not exist
    file:
      path: /var/www/html/index.html
      state: absent
    become: true
