name: Lamp Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint Ansible Playbook
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: ansible-lint
      uses: ansible/ansible-lint-action@v4.1.0.post0
      with:
        targets: "ansible/*.yml"
        args: "-c ansible/.ansible-lint"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: playbooks
        path: ansible

  deploy_to_test:
    name: Deploy to test
    runs-on: ubuntu-latest
    needs: lint
    if: github.ref == 'refs/heads/main'
    environment: Test

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: playbooks
        path: ansible

    - name: Run Ansible playbook
      uses: dawidd6/action-ansible-playbook@v2.5.0
      with:
        playbook: playbook.yml
        directory: ansible
        vault_password: ${{ secrets.VAULT_PASSWORD }}
        options: |
          --inventory inventory-test.yml 

  deploy_to_prod:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: deploy_to_test
    if: github.ref == 'refs/heads/main'
    environment: Production

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: playbooks
        path: ansible
    - name: Run ansible Playbook
      uses: dawidd6/action-ansible-playbook@v2.5.0
      with:
        playbook: playbook.yml
        directory: ansible
        vault_password: ${{ secrets.VAULT_PASSWORD }}
        options: |
          --inventory inventory-prod.yml

