name: Lamp Deployment

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Ansible Playbook
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Linting
      uses: ansible/ansible-lint-action@main
      with:
        override-deps: |
          ansible==2.9
          ansible-lint==4.2.0
        targets: |
          ansible/playbook.yml
          ansible/inventory.yml
        args: "-c ansible/.ansible-lint"