name: Lamp Deployment

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Ansible Playbook
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: ansible-lint
      uses: ansible/ansible-lint-action@ec3a7ce113134d7a93b817d10a8272cb61118579
      with:
        override-deps: |
          ansible==2.9
          ansible-lint==4.2.0
        targets: |
          ansible/playbook.yml
          ansible/inventory.yml
        args: "-c ansible/.ansible-lint"